// import "./globals.css";
import Nav from "@/components/Nav";
import "@/styles/globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <header className="site-header">
          <div className="header-inner">
          <img src="\img\logo LA + montaña.jpg" alt="Bodegas Robertson" />
            <div className="brand">
            <h1>Luz de los Andes</h1>
              <span className="divider"></span>
              <h2>·WINES·</h2>
          </div>
          </div>
        </header>
        <Nav />

        <main class="page-transition">
          {children}
        </main>

        <footer>
          <p>Diseñado por Ignacio Robertson - &copy; 2026</p>
        </footer>
      </body>
    </html>
  );
}
