// import "./globals.css";
import Nav from "@/components/Nav";
import "@/styles/globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <header>
          <img src="\img\logo LA + montaña.jpg" alt="Bodegas Robertson" />
          <div>
            <h1>Luz de los Andes</h1>
            <h2>·WINES·</h2>
          </div>
        </header>
        <Nav />
        {children}
        <footer>
          <p>Diseñado por Ignacio Robertson - &copy; año</p>
        </footer>
      </body>
    </html>
  );
}
